dist: trusty
language: java
jdk: openjdk7

install: mvn install

after_success:
  - gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import deployment/signingkey.asc
  - gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring --import deployment/signingkey.asc
  - ./deployment/deploy.sh

env:
  global:
  - secure: LVJ+XWfgXAgiaL3Fg2lAWLVfHiWqbiffAg/QIwVo4ohSP2O+vEhaPV9dwIpfpAGbat10Q8vv9/8JvGHD1eNxdPlQpCI8u+WAzxgwrMrPwoZxEQ2q94sHtxIC0sLaJr3Ak2Y1Y/kFDQDIwVOmJ3TGnF8f1aRXfKFEV6xBbbErKUz7bmBdLkHS/baf6ucOKNBAStVnvUEkmw+1iWzT9ASg1kbcRVZdZAhbqLSgSmx9HgeqiEkMuAXWlFGzmRjAxwRSTCW0La7fXWLXV3PCXP9ABZ41XnuIw0awYQYae1c3Q3BYk9W/T/X7jPWqA97mj2k9cdlC4hEOG/kh5rAFJhSzBgm5RhFRmAG+5JX4lLnutkOw9LOXV/YALibF0BUkl1GFnuJaWo6yYZC4kclX9xoskdFhdoOlv4LcsYgB+nZ3VfhWA85wmnzXefbC20Xhrqzj61OetzP7fsvmU/N065+71DSfD1MnLep6enrPRU9MTIR5orK4DYeXjvv5uVIE+yWgClFQHfJO6Q9uCp2pv1tOlLFe9wfbN5Ib4ioZONtQOYWEdpD9IbrXECGJsv1kY/WWHMNyJYrySLl35nTbrLnSLc3/Ye25AFb56h6X9Y+k/oUOmNbK2sEXDgEsxh5JKDsu9eJaRxjQfLUPtWDVbvV3zt2qFaWz3rCLA2iEhknMPQc=
  - secure: D59IAmqAt02p3DznJTYuO2hdK0whu3HNqJnjK3N9eZtVtuKniY7Y8zaXN0WCf0UPVNrBeNXeaObRKY7DcHEHPspfIrLkwJsj3hX4SqhIEc7dPDCDx7vC1G5Jo1fjIIFnssOMJM8+zj2bkkSbQWu03kluufGliBBUDLY1Mtv3/FJUl12mOS9f2GmD2PF1KbX+F5PtsqFhlb+4Vi6RoU13LCNJd/xXCOetSGo0YXrPHVgC6GB6rNSzL2dcVm78gD7VAwzsQEBaXYZe/QysbAo5YH4FfAeuGkJ9aRNzMZEDH9oK5omU3u9NQ3657Il9xIiaSCJPX6CaCcHmIqK+WrI522afQ858utDjRyZ7jPA2naqcNvB9DPaBC31EWG2DIITCaBgdXDYeRv4OFuB+vCfci9v8zxNBR7R7/8DrQPbRF3PDlPXaIrlkLqRm7Zeiu4FNA0ebfyL1SdtuICmADIyDvRIISFc6dpTfW/96X5Z3+UP3xZvU0wvbc4PiEVCsAJqBGCa1N1o4Ww3V6PW6hXZXD6gQ17lZfRayLCFhxzDvIJ52FWdYNXk239u/e9alB+B4hGxdYfoJV4qdurKtEa2b10pZm4LmmIXs2gNzWYAIe9u9BJhxsD4HHknVod7oukxKx55agWy4ECflSTXHc3hzrEYsY125yQ4A2cPbQVKFQIg=
  - secure: J9yLiVzA4vmD5jH8KAByawi7vMgjxbmDWdg0LkFCBdx+4fptJq6OhzRqxNOBn42bsUzAgO227mRitjSoUjGcwc1LgeceV/d1b6Lfs7QQrsre/Zgm2I41J2NNMCBH9vZCSxc/M8YqkXkskxqazNzISMihi3m+e/mf6hre/EfdzdH78uAn8JJruFMp49x7ap4k4lXCYtkti7kKjTe7qPeZMNvEKq28mvaQTLR5hb0byg06ibqN7ShbOK/h7U5PSp4dd78FIy3PWhq8kA9Jz8iDY8yzfiuptaq9kq+7L5EpPwt5cikL91nzqtLE/qfqpPSb3s9n+riP1cZZPGnDSBieyUqVuHrGTE8xmy5ZJjnxVzm1VD8zqDplWdXKdP0M9zCbNJuPhdvDjiiGyu8BHraRzg1aXb+MZ4s8lgVnnv/RI7VuY/Xo7VLsccdvURAH4jBUIsK+P9r7BnXt1HPFjUBM0X1llrFrWMYOGjdG9p6j/hMscJSitUJ5DAAgdVDRIva/LtsznAUXndpBTWbNqpsuhlG1CxNsbevi93RhHKJb2CS9XAfoF4cp1p0snyl0SpvGyzEKA6oaHcJdEpCek6Fxmutv7Tk2vnwW1+kIwv4fpjcyv3GNOAajkNmcTNSqDid8iXYnv97zlVdLnu+azK05SFmBUXVqUStynRKxVj8lYgE=

before_install:
  - openssl aes-256-cbc -K $encrypted_b172aa195e02_key -iv $encrypted_b172aa195e02_iv -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d

cache:
  directories:
    - ~/.m2/repository
